remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme
theme: Midnight
title: Simple Blog
author: Kenny Nguyen
description: Just a Simple blog about some things I've toyed with
